config/routes.rb
Rails.application.routes.draw do
  root 'homes#index'
  resources :users, :games
  get '/points-table', :to => 'homes#points_table', as: :points_table
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/game.rb
class Game < ApplicationRecord
  has_many :players, dependent: :destroy

  accepts_nested_attributes_for :players
  validates_presence_of :name
end

app/models/player.rb
class Player < ApplicationRecord
  belongs_to :game
  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  validates :phone_number,
            numericality: true,
            length: { minimum: 10, maximum: 12,
            message: "minimum 10 and maximum 12 numbers allowded." }
  validates :email,
            presence: true,
            format: { with: /\A([\w+\-].?)+@[a-z\d\-]+(\.[a-z]+)*\.[a-z]+\z/i, 
                        message: 'is invalid'}
  validates :name,
            presence: true
 
  has_many :players, dependent: :destroy
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
	protect_from_forgery with: :exception
end

app/controllers/games_controller.rb
class GamesController < ApplicationController
  before_action :find_game, except: [:index, :new, :create]

  def index
    @games = Game.all
    respond_to do |format|
      format.json { render json: @games, status: 200 }
      format.html
    end
  end

  def show
    # games = @game.participants.pluck(:game_id).uniq
    # @win = 0; @los = 0
    # Game.where(id: games).each do |game|
    #   game.participants.order('score DESC').first.Game_id == @game.id ? @win +=1 : @los +=1
    # end
  end

  def new
    @game = Game.new
    2.times do
      player = @game.players.build
    end
  end

  def create
    @game = Game.new(game_params)

    respond_to do |format|
      if @game.save
        format.html { redirect_to games_path, notice: 'Game created.' }
        format.json { render :show, status: 200, location: @game }
      else
        format.html { render :new }
        format.json { render json: @game.errors, status: 404 }
      end
    end
  end

  def update
    respond_to do |format|
      if @game.update(game_params)
        format.html { redirect_to games_path, notice: 'Game updated.' }
        format.json { render :show, status: 200, location: @game }
      else
        format.html { render :edit }
        format.json { render json: @game.errors, status: 404 }
      end
    end
  end

  def destroy
    @game.destroy
    respond_to do |format|
      format.html { redirect_to games_url, notice: 'Game destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    def find_game
      @game = Game.find(params[:id])
    end

    def game_params
      params.require(:game).permit(
        :name,
        :game_date,
        :game_time,
        :rules,
        players_attributes: [:user_id, :game_score]
      )
    end
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def points_table
    user_ids = User.joins(:players).group('users.id').having("count(players.id)>=10")
    @leaderboard_users = User.where(id: user_ids).includes(:players).order("players.game_score desc").limit(10)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :find_user, except: [:index, :new, :create]

  def index
    @users = User.all
    respond_to do |format|
      format.json { render json: @users, status: 200 }
      format.html
    end
  end

  def show
    games = @user.players.pluck(:game_id).uniq
    @win = 0; @los = 0
    Game.where(id: games).each do |game|
      game.players.order('game_score DESC').first.user_id == @user.id ? @win +=1 : @los +=1
    end
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to users_path, notice: 'User created.' }
        format.json { render :show, status: 200, location: @user }
      else
        format.html { render :new }
        format.json { render json: @user.errors, status: 404 }
      end
    end
  end

  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to users_path, notice: 'User updated.' }
        format.json { render :show, status: 200, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: 404 }
      end
    end
  end

  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: 'User destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    def find_user
      @user = User.find(params[:id])
    end

    def user_params
      params.require(:user).permit(
        :email,
        :name,
        :phone_number,
        :alias,
      )
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/games_helper.rb
module GamesHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/games/_form.html.haml
= form_with(model: game, local: true) do |form|
  .field
    = form.label :name
    = form.text_field :name
  .field
    = form.label :game_date
    = form.date_field :game_date
  .field
    = form.label :game_time
    = form.time_field :game_time
  .field
    = form.label :rules
    = form.text_area :rules
  = form.fields_for :players do |builder, i|
    %p
    %strong
      Player #{i}#{i}
    = render 'select_players', :f => builder
  - if game.errors.present?
    .error
      %ul
        Total #{game.errors.count} Errors encountered
        - game.errors.full_messages.each do |message|
          %li= message
  .actions
    = form.submit

app/views/games/_select_players.html.haml
.field
  = f.label "player"
  = f.select :user_id, options_for_select(User.all.pluck(:name, :id)), {:prompt => 'select somethig'}, :class => "form-control select2"
.field
  = f.label "score"
  = f.number_field :game_score

app/views/games/edit.html.haml
%h1 Edit new game
= render 'form', game: @game

app/views/games/index.html.haml
= link_to 'Back', root_path
%h1 Games list
%p= notice
.col-xs-12
  .box
    .box-header
      .box-body
        %table#example2.table.table-bordered.table-striped
          %thead
            %tr
              %th Name
              %th Date
              %th Time
              %th Rules
              %th Actions
          %tbody
            - @games.each do |game|
              %tr
                %td= game.name
                %td= game.game_date
                %td= game.game_time
                %td= game.rules
                %td= link_to 'Show', game
                %td= link_to 'Edit', edit_game_path(game)
                %td= link_to 'Destroy', game, method: :delete, data: { confirm: 'Are you sure?' }
%br
= link_to 'Create New Game', new_game_path

app/views/games/new.html.haml
%h1 Crete new game
= render 'form', game: @game

app/views/games/show.html.haml
%h1 Games#show
%p Find me in app/views/games/show.html.haml

app/views/homes/index.html.haml
%p 
  = link_to "Users", users_path
%p 
  = link_to "Games", games_path
%p 
  = link_to "Leaderboard", points_table_path

app/views/homes/points_table.html.haml
= link_to 'Back', root_path
%h1 Game scorecard
.col-xs-12
  .box
    .box-header
      .box-body
        %table#example2.table.table-bordered.table-striped
          %thead
            %tr
              %th Name
              %th Total games
              %th Average Score
              %th
          %tbody
            - @leaderboard_users.each do |lu|
              %tr
                %td= lu.name
                %td= lu.players.count
                %td= (lu.players.pluck(:game_score).sum/lu.players.pluck(:game_score).count).round

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ScrabbleResults</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/users/_form.html.haml
= form_with(model: user, local: true) do |form|
  .field
    = form.label :email
    = form.text_field :email
  .field
    = form.label :name
    = form.text_field :name
  .field
    = form.label :phone_number
    = form.text_field :phone_number
  .field
    = form.label :alias_name
    = form.text_field :alias
  - if user.errors.present?
    .error
      %ul
        Total #{user.errors.count} Errors encountered
        - user.errors.full_messages.each do |message|
          %li= message
  .actions
    = form.submit

app/views/users/edit.html.haml
%h1 Edit User
= render 'form', user: @user

app/views/users/index.html.haml
= link_to 'Back', root_path
%h1 Users list
%p= notice
.col-xs-12
  .box
    .box-header
      .box-body
        %table#example2.table.table-bordered.table-striped
          %thead
            %tr
              %th Alias
              %th Name
              %th Number
              %th Email
              %th Actions
          %tbody
            - @users.each do |user|
              %tr
                %td= user.alias
                %td= user.name
                %td= user.phone_number
                %td= user.email
                %td= link_to 'Show', user
                %td= link_to 'Edit', edit_user_path(user)
                %td= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' }
%br
= link_to 'New user', new_user_path

app/views/users/new.html.haml
%h1 Crete new user
= render 'form', user: @user

app/views/users/show.html.haml
%p= "Phone: #{@user.phone_number}"
%p= "Name: #{@user.name}"
%p= @user.email
%p= "Number of wins: #{@win}"
%p= "Number of losses: #{@los}"
- gs = @user.players.pluck(:game_score)
%p= "Average score: #{gs.sum/gs.count}"
- players = @user.players.order('game_score DESC').first
%p= "Users High score: #{players.game_score}"
%p= "High score on: #{players.game_score}"
%p= "High score created against: #{players.game.players.where.not(user_id: @user.id).first.user.name}"